apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: delivery
  name: delivery
spec:
  replicas: 2
  selector:
    matchLabels:
      app: delivery
  template:
    metadata:
      labels:
        app: delivery
    spec:
      containers:
      - env:
        - name: ALL_IN_ONE_STORAGE_DIR
          value: /data
        - name: ALL_IN_ONE_DELIVERY_POSTGRES_DSN
          value: ${ALL_IN_ONE_DELIVERY_POSTGRES_DSN:-postgresql://all_in_one:local-development-only@postgres:5432/all_in_one}
        image: gcr.io/all-in-one-498012/delivery:latest
        name: delivery
        ports:
        - containerPort: 8000
