apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: erp
  name: erp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: erp
  template:
    metadata:
      labels:
        app: erp
    spec:
      containers:
      - env:
        - name: ALL_IN_ONE_STORAGE_DIR
          value: /data
        - name: ALL_IN_ONE_ERP_POSTGRES_DSN
          value: ${ALL_IN_ONE_ERP_POSTGRES_DSN:-postgresql://all_in_one:local-development-only@postgres:5432/all_in_one}
        image: gcr.io/all-in-one-498012/erp:latest
        name: erp
        ports:
        - containerPort: 8000
