apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jobs
  name: jobs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jobs
  template:
    metadata:
      labels:
        app: jobs
    spec:
      containers:
      - env:
        - name: ALL_IN_ONE_STORAGE_DIR
          value: /data
        - name: ALL_IN_ONE_PRIVATE_DOCUMENT_DIR
          value: /private-documents
        - name: ALL_IN_ONE_DOCUMENT_ENCRYPTION_KEY
          value: ${ALL_IN_ONE_DOCUMENT_ENCRYPTION_KEY:-}
        - name: ALL_IN_ONE_JOBS_POSTGRES_DSN
          value: ${ALL_IN_ONE_JOBS_POSTGRES_DSN:-postgresql://all_in_one:local-development-only@postgres:5432/all_in_one}
        image: gcr.io/all-in-one-498012/jobs:latest
        name: jobs
        ports:
        - containerPort: 8000
