apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: marketplace
  name: marketplace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: marketplace
  template:
    metadata:
      labels:
        app: marketplace
    spec:
      containers:
      - env:
        - name: ALL_IN_ONE_STORAGE_DIR
          value: /data
        - name: ALL_IN_ONE_MARKETPLACE_POSTGRES_DSN
          value: ${ALL_IN_ONE_MARKETPLACE_POSTGRES_DSN:-postgresql://all_in_one:local-development-only@postgres:5432/all_in_one}
        image: gcr.io/all-in-one-498012/marketplace:latest
        name: marketplace
        ports:
        - containerPort: 8000
