apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mobility
  name: mobility
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mobility
  template:
    metadata:
      labels:
        app: mobility
    spec:
      containers:
      - env:
        - name: ALL_IN_ONE_STORAGE_DIR
          value: /data
        - name: ALL_IN_ONE_MOBILITY_POSTGRES_DSN
          value: ${ALL_IN_ONE_MOBILITY_POSTGRES_DSN:-postgresql://all_in_one:local-development-only@postgres:5432/all_in_one}
        image: gcr.io/all-in-one-498012/mobility:latest
        name: mobility
        ports:
        - containerPort: 8000
