apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: property
  name: property
spec:
  replicas: 2
  selector:
    matchLabels:
      app: property
  template:
    metadata:
      labels:
        app: property
    spec:
      containers:
      - env:
        - name: ALL_IN_ONE_STORAGE_DIR
          value: /data
        - name: ALL_IN_ONE_PROPERTY_POSTGRES_DSN
          value: ${ALL_IN_ONE_PROPERTY_POSTGRES_DSN:-postgresql://all_in_one:local-development-only@postgres:5432/all_in_one}
        image: gcr.io/all-in-one-498012/property:latest
        name: property
        ports:
        - containerPort: 8000
