apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: stock
  name: stock
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stock
  template:
    metadata:
      labels:
        app: stock
    spec:
      containers:
      - env:
        - name: ALL_IN_ONE_STORAGE_DIR
          value: /data
        - name: ALL_IN_ONE_STOCK_POSTGRES_DSN
          value: ${ALL_IN_ONE_STOCK_POSTGRES_DSN:-postgresql://all_in_one:local-development-only@postgres:5432/all_in_one}
        image: gcr.io/all-in-one-498012/stock:latest
        name: stock
        ports:
        - containerPort: 8000
